// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVvtR3p7FUmudkMoiHd5SExIdX5RvYrg',
    appId: '1:1047938981596:web:07a0d83563d7be9ee95e19',
    messagingSenderId: '1047938981596',
    projectId: 'messagingapp-4651c',
    authDomain: 'messagingapp-4651c.firebaseapp.com',
    storageBucket: 'messagingapp-4651c.appspot.com',
    measurementId: 'G-3JFN8T30TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhUhqj9TA7bUXgtotndkZG3KpG_2A04WU',
    appId: '1:1047938981596:android:67b356abccd3346ce95e19',
    messagingSenderId: '1047938981596',
    projectId: 'messagingapp-4651c',
    storageBucket: 'messagingapp-4651c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNE3PnrKmCiPBfgt_CrFxl6I9bHmeO3Hs',
    appId: '1:1047938981596:ios:936a0d30ffbc3892e95e19',
    messagingSenderId: '1047938981596',
    projectId: 'messagingapp-4651c',
    storageBucket: 'messagingapp-4651c.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNE3PnrKmCiPBfgt_CrFxl6I9bHmeO3Hs',
    appId: '1:1047938981596:ios:936a0d30ffbc3892e95e19',
    messagingSenderId: '1047938981596',
    projectId: 'messagingapp-4651c',
    storageBucket: 'messagingapp-4651c.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVvtR3p7FUmudkMoiHd5SExIdX5RvYrg',
    appId: '1:1047938981596:web:d803d1cbcb2fd152e95e19',
    messagingSenderId: '1047938981596',
    projectId: 'messagingapp-4651c',
    authDomain: 'messagingapp-4651c.firebaseapp.com',
    storageBucket: 'messagingapp-4651c.appspot.com',
    measurementId: 'G-QNLN64M4MY',
  );

}